name: stap_trial2
channels:
  - conda-forge
dependencies:
  - pip>=22.0.4
  - python=3.8.10
  - setuptools==65.5.0
  - wheel=0.38.4  # Fix for Issue #160: https://github.com/openai/gym/issues/3202#issuecomment-1513593788
  - swig
  - pip:
    # works for regular pip packages
    - matplotlib
    - numpy
    - scipy
    - imageio
    - pillow
    - scikit-image
    - pyyaml
    - pandas
    - seaborn
    - shapely
    - functorch==0.2.1
    - torch==1.12.1
    - torchvision==0.13.1
    - torchaudio==0.12.1
    - tensorboard
    - tqdm
    - box2d-py
    - gym>=0.25
    - pybullet
    - ctrlutils==1.4.1
    # -> now in third party: - pysymbolic @ git+https://github.com/kevin-thankyou-lin/symbolic
    - spatialdyn==1.4.4
    - tyro
    - opencv-python
    - atomicwrites
    - pexpect
    - gdown
    - black
    - mypy
    - flake8
    - shapely
